### PR TITLE
Scala 2.13.0

### PR DESCRIPTION
**Pull request by xuwei-k**

### CODE REVIEW

**Comment by Krever** [comment]
@bkirwi do you think you could merge and release this?

**Comment by bkirwi** [comment]
Hmm... I've been holding out on a merge because cats, our main dependency,
doesn't have a stable release on 2.13 yet. (And the current milestone seems
likely to break bincompat.) Would you still want a release under those
conditions?

**Comment by Krever** [comment]
This sounds reasonable. I already rebased this PR and published locally and I don't plan to release anytime soon so form me its fine for at least week or two. Do you know when the stable cats is planned?

**Comment by kailuowang** [comment]
> holding out on a merge because cats, our main dependency, doesn't have a stable release on 2.13 yet. (And the current milestone seems likely to break bincompat.)

That's correct. Although, a milestone deline release will be helpful...(at least I can use it. :) )

**Comment by bkirwi** [comment]
Aight, I can milestone if it'll help folks... will comment here when that's done.

**Comment by bkirwi** [comment]
Released as `0.7.0-M0`... holler if you run into any issues.

**Comment by kailuowang** [comment]
Thanks!

**Pull request merged**
