### PR TITLE
Update cats-effect to 3.0.0-RC2

### PR DESCRIPTION
**Pull request by kubukoz**
Just checking if there will be any issues when CE3 actually comes out. Apparently not, since IOApp does most of the heavy lifting.

### CODE REVIEW

**Comment by kubukoz** [comment]
Apparently the build is a ScalaJS version issue.

**Comment by bkirwi** [comment]
Thanks for checking!

And yep, not expecting any issues... our usage is very simple.

**Comment by catostrophe** [comment]
Can we have this branch released as a milestone?

**Comment by kubukoz** [comment]
cc @bkirwi @johnynek

**Comment by johnynek** [comment]
Is there a way we can have the PR without the incidental reformatting? It makes it harder to understand the meat of the diff. I am not very opinionated about the style, but I'd really like to see the changes in two separate PRs.

**Comment by kubukoz** [comment]
It's the style from .scalafmt.conf, I think the sbt files were just not formatted before... AFAICS the only relevant change in build.sbt is the version bump, so I can try to bring back just that one.

**Comment by kubukoz** [comment]
That should do it.

**Comment by kubukoz** [comment]
And this actually does.

**Comment by bkirwi** [comment]
Looks reasonable! I should be able to cut a milestone in the next couple days.

I suppose this is a breaking change, so I guess that pushes us to 2.0?

**Comment by kubukoz** [comment]
Yeah, I think so... also might want to add a version scheme: https://github.com/typelevel/cats/issues/3780

**Comment by bkirwi** [comment]
Aight, this is out as `2.0.0-RC1`. Let me know if you run into any issues!

**Comment by labra** [comment]
Thanks for the release. We tried it in the [shex-s project](https://github.com/weso/shex-s/) and it compiles and runs without arguments. However, when we try to run it with some arguments, it raises the exception: 

```
error] java.lang.NoClassDefFoundError: cats/effect/Sync
[error]         at es.weso.shexs.Main$.infoError(Main.scala:199)
[error]         at es.weso.shexs.Main$.$anonfun$main$3(Main.scala:195)
. . .
```

It seems there is some dependency on Cats-effec 2.0 but I don't know how to detect which one it is.

**Comment by catostrophe** [comment]
@labra check `dependencyTree` in your project.

I have upgraded `decline` and can confirm that it doesn't pull CE2 dependency

**Comment by labra** [comment]
Yes, indeed, I checked the dependencies again and the problem was that I had a dependency on `console4cats`. I removed it now and it works! Thanks for the update of decline to CE3!

**Comment by kubukoz** [comment]
I do recommend upgrading to sbt 1.5.0-RC1 ASAP, if you have conflicting versions of cats-effect it'll break the build even before you compile! (thanks to the `versionScheme` setting)

**Pull request merged**
