### PR TITLE
Misc. updates including refined

### PR DESCRIPTION
**Pull request by travisbrown**
Bumping refined from 0.8 to 0.9 is the only important thing here, but I thought I might as well do the rest while I was here.

### CODE REVIEW

**Comment by johnynek** [comment]
Cool. I need to try refined!

**Comment by bkirwi** [comment]
This is great! Thanks for keeping us up.

**Comment by bkirwi** [comment]
Hmm... it looks like one of these tweaks might have broken sonatype publishing? (Or perhaps that broke on its own in the last few weeks, though we haven't made any other build changes.)

Might be a few days before I have a chance to mess with this again. Are you blocked waiting on the new refined version?

**Comment by bkirwi** [comment]
Never mind, the problem was me! (Had to set up 1.1 for sonatype publishing.) This is now being released as `0.4.2`.

**Comment by travisbrown** [comment]
@bkirwi Sorry, should have flagged that. Thanks for publishing!

**Pull request merged**
