### PR TITLE
Bare bones Scala 3 build support

### PR DESCRIPTION
**Pull request by keynmol**

### CODE REVIEW

**Comment by kubukoz** [comment]
Was this the day of the brownout? The build seems to fail for no reason...

**Comment by SethTisue** [comment]
Looks like the usual problem where Travis-CI has an antiquated sbt-extras that doesn't work with current (1.4.8+) sbt versions; see the "Migration note for Travis CI" at https://eed3si9n.com/sbt-1.4.8

also I notice that CI is running on travis-ci.org rather than .com, that probably isn't going to keep working at all for much longer

**Comment by kubukoz** [comment]
Needs https://github.com/typelevel/discipline-scalatest/pull/184

Here are other changes that might be useful:

```diff
diff --git a/build.sbt b/build.sbt
index 433fbfc..380b263 100644
--- a/build.sbt
+++ b/build.sbt
@@ -7,7 +7,7 @@ val mimaPreviousVersion = "1.0.0"
 
 lazy val Scala212 = "2.12.12"
 lazy val Scala213 = "2.13.3"
-lazy val Scala3 = "3.0.0-RC2"
+lazy val Scala3 = "3.0.0"
 
 val defaultSettings = Seq(
   scalaVersion := Scala213,
@@ -74,8 +74,8 @@ lazy val noPublishSettings = Seq(
   publishArtifact := false
 )
 
-val catsVersion = "2.5.0"
-val catsEffectVersion = "3.0.2"
+val catsVersion = "2.6.1"
+val catsEffectVersion = "3.1.1"
 
 lazy val root =
   project.in(file("."))
@@ -90,7 +90,7 @@ lazy val decline =
       libraryDependencies ++= {
         if(scalaVersion.value.startsWith("2."))
           Seq(compilerPlugin("org.typelevel" % "kind-projector" % "0.11.3" cross CrossVersion.full))
-        else 
+        else
           Seq.empty
         }
     )
@@ -100,7 +100,7 @@ lazy val decline =
       libraryDependencies ++= Seq(
         "org.typelevel"  %%% "cats-core"            % catsVersion,
         "org.typelevel"  %%% "cats-laws"            % catsVersion % Test,
-        "org.typelevel"  %%% "discipline-scalatest" % "2.1.3"  % Test
+        "org.typelevel"  %%% "discipline-scalatest" % "2.1.5-SNAPSHOT"  % Test
       ),
     )
     .jvmSettings(

```

**Comment by bkirwi** [comment]
`discipline-scalatest` is now updated; currently waiting on https://github.com/cquiroz/scala-java-time/pull/286.

**Comment by bkirwi** [comment]
Wanted to make sure I said thanks for this - the changes suggested here were the basis of our 3.0 support. Appreciate y'all getting this rolling!

**Pull request closed without merging**
