### PR TITLE
scala 2.12.4, cats 1.0.0

### PR DESCRIPTION
**Pull request by tpolecat**

### CODE REVIEW

**Comment by tpolecat** [comment]
Hi, can we get a release for cats 1.0?

**Comment by johnynek** [comment]
I think we actually need 1.0.1.

PS: this is why binary deps suck. Look at how much churn cats releases cause.

**Comment by bkirwi** [comment]
Sorry, been travelling -- I'll aim to bump to 1.0.1 and cut a release for
this tomorrow.

**Comment by bkirwi** [comment]
Aight, bumped to cats `1.0.1` and released as `0.4`. Let me know if you run into issues! I'll start pointing folks to 0.4 on the doc site within the next couple days.

**Comment by tpolecat** [comment]
Works great, already published my downstream stuff. Thanks!

**Pull request merged**
