### PR TITLE
add Scala 2.13.0-M5 to cross-build

### PR DESCRIPTION
**Pull request by SethTisue**
and bump versions on assorted other things

### CODE REVIEW

**Comment by SethTisue** [comment]
needed: https://github.com/cquiroz/scala-java-time/issues/91

**Comment by SethTisue** [comment]
note that your `.travis.yml` was misconfigured and wasn't actually testing the different Scala versions, I included a fix

**Comment by SethTisue** [comment]
waiting for artifacts to show up at https://repo1.maven.org/maven2/io/github/cquiroz/scala-java-time_sjs0.6_2.13.0-M5/2.0.0-RC1/

**Comment by SethTisue** [comment]
CI is green now!

**Comment by bkirwi** [comment]
Thanks for this, especially the build cleanup! Let me know if you'd like a release out for this as well?

**Comment by SethTisue** [comment]
in general, we're always happy to have more libraries published for Scala milestones, since it enables more people to try the milestones.

I have no more specific need for a release.

**Pull request merged**
