### PR TITLE
Add Show[Help] instance

### PR DESCRIPTION
**Pull request by chuwy**
IMO toString usage should be discouraged, but at the same time we would like to not break the compatibility.

If this is a right direction - I can change/add more tests.

### CODE REVIEW

**Comment by bkirwi** [comment]
hey, thanks for the pr!

i'm disinclined to deprecate the toString method, for a couple reasons:
- imo toString is fine in non-polymorphic contexts, and it’s more
accessible for folks who aren't super familiar with cats yet.
- there’s some demand for parametrized help rendering... if eg. you wanted
to set an indentation level for the rendered help, there’s nowhere obvious
to put that for a show instance. obviously not a concern yet! but we might
have to switch back to a method on help again soon anyways.

otoh, there’s no reason not to add the show instance, and it’s definitely
smart! i'd be quite happy to accept the additive parts of this.

**Comment by chuwy** [comment]
Thanks @bkirwi! I still see a lot of value in getting rid of ubiqutous JVM methods, but I get that. I'll remove the deprecation and add some tests. Cheers!

**Comment by chuwy** [comment]
Hey @bkirwi! I updated the PR.

**Comment by bkirwi** [comment]
Great! Thanks in particular for the test.

I'll get this in as soon as I have some unrelated issues with Travis sorted out...

**Pull request merged**
